### ISSUE TITLE
Mac binaries on CRAN

### ISSUE THREAD

**Issue by tmelliott** [lawremi/RGtk2#2]
I'm interested to know if 
1. you're aware the mac binaries are no longer avilable on CRAN  (since R 3.4), and 
2. if so, any idea if/when this will be remedied? 

I realise this probably isn't anything to do with your package, but I don't want to bug the CRAN people if there's already action underway!

Since we are distributing learning software, compiling from source isn't an option since it's no longer straightforward on Mac. Fortunately, we can still get it running using R 3.2, but that's only OK until another dependency requires R >3.3 ..!!

**Comment by lawremi** [comment]
Sorry for this inconvenience. I've notified Simon a while ago I think but he hasn't taken any action to my knowledge. Maybe some encouragement and reminding by the users could help him find the time to take care of this.

**Comment by lawremi** [comment]
I will push it to CRAN tonight (Kurt is now bugging me about it). Closing this for now.

**Comment by tmelliott** [comment]
Hi @lawremi - I wont open a new issue yet as I don't belive it's a problem with the package, but I finally had a chance to talk to Simon and he has mostly fixed the CRAN problem - RGtk2 binaries are now available for macOS...

However, there's a linking problem with scale objects getting a segfault:
```r
library(RGtk2)
gtkHScaleNewWithRange(0, 5, 1)
```
This is only occuring on macOS with the latest binaries from CRAN. 

I'm still waiting to hear back from Simon regarding this latest issue but I thought I'd let you know some progress has been made (and on the off chance you know what the problem is!).
