### ISSUE TITLE
Next CRAN release?

### ISSUE THREAD

**Issue by yihui** [lawremi/RGtk2#4]
The most recent commit cfe87505172b813850ecda371a00a92f6caac88c was what I have been waiting for a long time. Unconditionally including `gdk/gdkx.h` has caused [so much frustration](https://www.google.com/search?q=fatal+error%3A+%27gdk%2Fgdkx.h%27+file+not+found&oq=fatal+error%3A+%27gdk%2Fgdkx.h%27+file+not+found&aqs=chrome..69i57j69i61l2&sourceid=chrome&ie=UTF-8) in installing RGtk2 on macOS, and it was extremely inconvenient to fix the problem. Now we can just `brew install gtk+ && R CMD INSTALL RGtk2`. That is just so awesome. Could you consider a new CRAN release soon? Thanks!

**Comment by yihui** [comment]
Similarly, it will be nice if you can release cairoDevice to CRAN, too (due to https://github.com/lawremi/cairoDevice/commit/8edf81638133253785e6b787f446b8acfaa0e8cb).

**Comment by lawremi** [comment]
Thanks for the reminder. These should be up on CRAN soon.
